### ISSUE TITLE
Having array of sub schemas fail

### ISSUE THREAD

**Issue by vmatekole** [mattyod/matic#20]
....

 "payout_methods": {
      "type": "object",
      "oneOf": [
        { "$ref": "#/definitions/bitcoin.json" },
        { "$ref": "#/definitions/sepa.json" },
        { "$ref": "#/definitions/uk_bank.json" }
      ]
    }

....

Error message:
/usr/local/lib/node_modules/jade/lib/runtime.js:231
  throw err;
        ^
TypeError: templates/mixins/itterate.jade:22
    20|             mixin itterate(item, item.title, obj)
    21|           else
  > 22|             - var schema = key.match(/^(properties)|(patternProperties)|(items)$/) ? obj : val
    23|             mixin itterate(item, name, schema)
    24|   else
    25|     dt

Cannot call method 'match' of undefined
    at Object.eval (eval at <anonymous> (/usr/local/lib/node_modules/jade/lib/index.js:216:8), <anonymous>:292:18)
    at Object.jade_mixins.itterate (eval at <anonymous> (/usr/local/lib/node_modules/jade/lib/index.js:216:8), <anonymous>:304:4)
    at Object.eval (eval at <anonymous> (/usr/local/lib/node_modules/jade/lib/index.js:216:8), <anonymous>:254:24)
    at Object.jade_mixins.itterate (eval at <anonymous> (/usr/local/lib/node_modules/jade/lib/index.js:216:8), <anonymous>:304:4)
    at Object.eval (eval at <anonymous> (/usr/local/lib/node_modules/jade/lib/index.js:216:8), <anonymous>:295:24)
    at Object.jade_mixins.itterate (eval at <anonymous> (/usr/local/lib/node_modules/jade/lib/index.js:216:8), <anonymous>:304:4)
    at Object.eval (eval at <anonymous> (/usr/local/lib/node_modules/jade/lib/index.js:216:8), <anonymous>:295:24)
    at Object.jade_mixins.itterate (eval at <anonymous> (/usr/local/lib/node_modules/jade/lib/index.js:216:8), <anonymous>:304:4)
    at jade_debug.unshift.lineno (eval at <anonymous> (/usr/local/lib/node_modules/jade/lib/index.js:216:8), <anonymous>:486:24)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/jade/lib/index.js:216:8), <anonymous>:495:4)

**Comment by mattyod** [comment]
The template you are using [this one I assume](https://github.com/mattyod/matic-draft4-example/blob/master/templates/mixins/itterate.jade#L22) is expecting to find a either a properties, patternProperties or items attribute at the root of your schema.

You could either add one [as in the example](https://github.com/mattyod/matic-draft4-example/blob/master/schemas/example.json) or adapt your template accordingly.
